# Generated by Django 6.0.1 on 2026-02-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_feature_companyfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'permissions': [('manage_company_features', 'Can manage company feature activation')], 'verbose_name_plural': 'companies'},
        ),
    ]
