# Generated by Django 6.0.1 on 2026-02-12 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_legacy_employees(apps, schema_editor):
    table_names = schema_editor.connection.introspection.table_names()
    if "users_employee" not in table_names:
        return

    Employee = apps.get_model("companies", "Employee")
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT id, created_at, company_id, user_id
            FROM users_employee
            """
        )
        rows = cursor.fetchall()

    existing_ids = set(
        Employee.objects.using(db_alias).values_list("id", flat=True)
    )

    for row in rows:
        row_id, created_at, company_id, user_id = row
        if row_id in existing_ids:
            continue
        Employee.objects.using(db_alias).create(
            id=row_id,
            created_at=created_at,
            company_id=company_id,
            user_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="employees", to="companies.company")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="employee_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.RunPython(copy_legacy_employees, migrations.RunPython.noop),
    ]
