# Generated by Django 6.0.1 on 2026-02-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_backfill_default_feature_and_admin_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
    ]
