# Generated by Django 6.0.1 on 2026-02-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'permissions': [('manage_company_features', 'Can manage company feature activation')], 'verbose_name_plural': 'companies'},
        ),
    ]
