# Generated by Django 6.0.1 on 2026-02-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='companies.company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.itemtype')),
            ],
            options={
                'permissions': [('view_financial_dashboard', 'Can view warehouse financial dashboard')],
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('new', 'new'), ('used', 'used'), ('damaged', 'damaged'), ('sold', 'sold')], max_length=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.item')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_item_type_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_manufacturer_name_per_company'),
        ),
    ]
