# Generated by Django 5.2.7 on 2025-10-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('plc', 'plc'), ('sensor', 'sensor'), ('actuator', 'actuator'), ('hmi', 'hmi'), ('plc_expansion', 'plc_expansion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemunit',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used'), ('damaged', 'damaged'), ('sold', 'sold')], max_length=10),
        ),
    ]
