# Generated by Django 5.2.7 on 2025-12-30 19:52

from django.db import migrations
from warehouse.models import ItemType


def create_item_types(apps, schema_editor):
    values = [
        "plc",
        "sensor",
        "actuator",
        "hmi",
        "plc_expansion",
    ]

    for value in values:
        ItemType.objects.get_or_create(name=value)


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_itemtype'),
    ]

    operations = [
        migrations.RunPython(create_item_types),
    ]
