# Generated by Django 5.2.7 on 2025-12-30 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20251230_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.itemtype'),
        ),
    ]
