# Generated by Django 5.2.7 on 2025-12-30 19:58

from django.db import migrations


def migrate_item_types(apps, schema_editor):
    Item = apps.get_model("warehouse", "Item")
    ItemType = apps.get_model("warehouse", "ItemType")

    for item in Item.objects.all():
        item.type_new = ItemType.objects.get(name=item.type)
        item.save(update_fields=["type_new"])


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_item_type_new'),
    ]

    operations = [
        migrations.RunPython(migrate_item_types),
    ]
