# Generated by Django 6.0.1 on 2026-02-12 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('warehouse', '0007_remove_item_type_new_alter_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('view_financial_dashboard', 'Can view warehouse financial dashboard')]},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='companies.company'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='companies.company'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_item_type_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_manufacturer_name_per_company'),
        ),
    ]
